Import the 7.0.10 release

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3,7 +3,7 @@
 # libraries VBox OSE depends on.
 
 #
-# Copyright (C) 2006-2022 Oracle and/or its affiliates.
+# Copyright (C) 2006-2023 Oracle and/or its affiliates.
 #
 # This file is part of VirtualBox base platform packages, as
 # available from https://www.virtualbox.org.
@@ -111,11 +111,13 @@ WITH_LIBVPX=1
 WITH_LIBOGG=0
 WITH_LIBVORBIS=0
 WITH_LIBTPMS=1
+WITH_LIBLZMA=1
 BUILD_LIBXML2=
 BUILD_LIBCURL=
 BUILD_LIBSSL=
 BUILD_LIBVPX=
 BUILD_LIBTPMS=
+BUILD_LIBLZMA=
 PASSIVE_MESA=0
 CC="gcc"
 CC32=""
@@ -732,9 +734,9 @@ EOF
         [ -n "$INCXML2" ] && I_INCXML2=`prefix_I "$INCXML2"`
         if test_compile "$LIBXML2 $LIBPTHREAD $I_INCXML2" xml2 xml2; then
           if test_execute; then
-            cnf_append "SDK_VBOX_LIBXML2_DEFS" "_REENTRANT" ## @todo get defines from --cflags
-            cnf_append "SDK_VBOX_LIBXML2_INCS" "$INCXML2"
-            cnf_append "SDK_VBOX_LIBXML2_LIBS" "`strip_l "$LIBXML2"`"
+            cnf_append "SDK_VBoxLibXml2_DEFS" "_REENTRANT" ## @todo get defines from --cflags
+            cnf_append "SDK_VBoxLibXml2_INCS" "$INCXML2"
+            cnf_append "SDK_VBoxLibXml2_LIBS" "`strip_l "$LIBXML2"`"
           fi
         fi
       fi
@@ -766,9 +768,9 @@ EOF
         [ -n "$INCXML2" ] && I_INCXML2=`prefix_I "$INCXML2"`
         if test_compile "$LIBXML2 $LIBPTHREAD $I_INCXML2" xml2 xml2; then
           if test_execute; then
-            cnf_append "SDK_VBOX_LIBXML2_DEFS" "_REENTRANT" ## @todo get defines from --cflags
-            cnf_append "SDK_VBOX_LIBXML2_INCS" "$INCXML2"
-            cnf_append "SDK_VBOX_LIBXML2_LIBS" "`strip_l "$LIBXML2"`"
+            cnf_append "SDK_VBoxLibXml2_DEFS" "_REENTRANT" ## @todo get defines from --cflags
+            cnf_append "SDK_VBoxLibXml2_INCS" "$INCXML2"
+            cnf_append "SDK_VBoxLibXml2_LIBS" "`strip_l "$LIBXML2"`"
           fi
         fi
       fi
@@ -888,9 +890,9 @@ extern "C" int main(void)
 EOF
     if test_compile "$INCCRYPTO $LIBCRYPTO" libcrypto openssl; then
       if test_execute nofatal; then
-        cnf_append "SDK_VBOX_OPENSSL_INCS" "`strip_I "$INCCRYPTO"`"
-        cnf_append "SDK_VBOX_OPENSSL_LIBS" "`strip_l "$LIBCRYPTO"`"
-        cnf_append "SDK_VBOX_BLD_OPENSSL_LIBS" "`strip_l "$LIBCRYPTO"`"
+        cnf_append "SDK_VBoxOpenSslStatic_INCS" "`strip_I "$INCCRYPTO"`"
+        cnf_append "SDK_VBoxOpenSslStatic_LIBS" "`strip_l "$LIBCRYPTO"`"
+        cnf_append "SDK_VBoxOpenSslBldProg_LIBS" "`strip_l "$LIBCRYPTO"`"
       fi
     fi
   fi
@@ -957,8 +959,8 @@ EOF
   if test_compile "$LIBZ $I_INCZ" zlib zlib; then
     if test_execute; then
       echo "if1of (\$(KBUILD_TARGET),darwin freebsd haiku linux)" >> $CNF
-      cnf_append " SDK_VBOX_ZLIB_LIBS" "`strip_l "$LIBZ"`"
-      cnf_append " SDK_VBOX_ZLIB_INCS" "$INCZ"
+      cnf_append " SDK_VBoxZlib_LIBS" "`strip_l "$LIBZ"`"
+      cnf_append " SDK_VBoxZlib_INCS" "$INCZ"
       echo "endif" >> $CNF
     fi
   fi
@@ -990,8 +992,8 @@ EOF
   if test_compile "$LIBLZF $I_INCLZF" liblzf liblzf nofatal; then
     if test_execute; then
       echo "if1of (\$(KBUILD_TARGET),darwin freebsd haiku linux)" >> $CNF
-      cnf_append " SDK_VBOX_LZF_LIBS" "`strip_l "$LIBLZF"`"
-      cnf_append " SDK_VBOX_LZF_INCS" "$INCLZF"
+      cnf_append " SDK_VBoxLzf_LIBS" "`strip_l "$LIBLZF"`"
+      cnf_append " SDK_VBoxLzf_INCS" "$INCLZF"
       echo "endif" >> $CNF
     fi
   else
@@ -1024,8 +1026,8 @@ EOF
   [ -n "$INCPNG" ] && I_INCPNG=`prefix_I "$INCPNG"`
   if test_compile "$LIBPNG $I_INCPNG" libpng libpng; then
     if test_execute; then
-      cnf_append "SDK_VBOX_LIBPNG_LIBS" "`strip_l "$LIBPNG"`"
-      cnf_append "SDK_VBOX_LIBPNG_INCS" "$INCPNG"
+      cnf_append "SDK_VBoxLibPng_LIBS" "`strip_l "$LIBPNG"`"
+      cnf_append "SDK_VBoxLibPng_INCS" "$INCPNG"
     fi
   fi
 }
@@ -1096,8 +1098,8 @@ EOF
     [ -n "$INCCURL" ] && I_INCCURL=`prefix_I "$INCCURL"`
     if test_compile "$LIBCURL $I_INCCURL" libcurl libcurl; then
       if test_execute; then
-        cnf_append "SDK_VBOX_LIBCURL_LIBS" "`strip_l "$LIBCURL"`"
-        cnf_append "SDK_VBOX_LIBCURL_INCS" "$INCCURL"
+        cnf_append "SDK_VBoxLibCurl_LIBS" "`strip_l "$LIBCURL"`"
+        cnf_append "SDK_VBoxLibCurl_INCS" "$INCCURL"
       fi
     fi
   fi
@@ -1765,8 +1767,8 @@ EOF
       [ -n "$INCVPX" ] && I_INCVPX=`prefix_I "$INCVPX"`
       if test_compile "$LIBVPX $I_INCVPX" vpx vpx; then
         if test_execute; then
-          cnf_append "SDK_VBOX_VPX_INCS" "$INCVPX"
-          cnf_append "SDK_VBOX_VPX_LIBS" "`strip_l "$LIBVPX"`"
+          cnf_append "SDK_VBoxLibVpx_INCS" "$INCVPX"
+          cnf_append "SDK_VBoxLibVpx_LIBS" "`strip_l "$LIBVPX"`"
           fi
       fi
     fi
@@ -1800,11 +1802,50 @@ EOF
       [ -n "$INCTPMS" ] && I_INCTPMS=`prefix_I "$INCTPMS"`
       if test_compile "$LIBTPMS $I_INCTPMS" libtpms libtpms nofatal; then
         if test_execute; then
-          cnf_append "SDK_VBOX_TPMS_INCS" "$INCTPMS"
-          cnf_append "SDK_VBOX_TPMS_LIBS" "`strip_l "$LIBTPMS"`"
+          cnf_append "SDK_VBoxLibTpms_INCS" "$INCTPMS"
+          cnf_append "SDK_VBoxLibTpms_LIBS" "`strip_l "$LIBTPMS"`"
         fi
       else
         echo "not found -- building libtpms from in-tree code."
+      fi
+    fi
+  fi
+}
+
+
+#
+# Check for liblzma
+#
+check_liblzma()
+{
+  if [ -z "$BUILD_LIBLZMA" ]; then
+    test_header liblzma
+    if which_wrapper pkg-config > /dev/null; then
+      liblzma_ver=`pkg-config liblzma --modversion 2>> $LOG`
+      if [ $? -eq 0 ]; then
+        FLGLZMA=`pkg-config liblzma --cflags`
+        INCLZMA=`strip_I "$FLGLZMA"`
+        LIBLZMA=`pkg-config liblzma --libs`
+      fi
+      cat > $ODIR.tmp_src.cc << EOF
+#include <cstdio>
+#include <lzma.h>
+extern "C" int main(void)
+{
+  lzma_stream strm = LZMA_STREAM_INIT;
+  uint32_t preset;
+  lzma_ret ret = lzma_easy_encoder(&strm, preset, LZMA_CHECK_CRC64);
+  printf("found, OK.\n");
+}
+EOF
+      [ -n "$INCLZMA" ] && I_INCLZMA=`prefix_I "$INCLZMA"`
+      if test_compile "$LIBLZMA $I_INCLZMA" liblzma liblzma nofatal; then
+        if test_execute; then
+          cnf_append "SDK_VBoxLibLzma_INCS" "$INCLZMA"
+          cnf_append "SDK_VBoxLibLzma_LIBS" "`strip_l "$LIBLZMA"`"
+        fi
+      else
+        echo "not found -- building liblzma from in-tree code."
       fi
     fi
   fi
@@ -1838,8 +1879,8 @@ EOF
     [ -n "$INCVRB" ] && I_INCVRB=`prefix_I "$INCVRB"`
     if test_compile "$LIBVRB $I_INCVRB" vorbis vorbis nofatal; then
       if test_execute; then
-        cnf_append "SDK_VBOX_VORBIS_INCS" "$INCVRB"
-        cnf_append "SDK_VBOX_VORBIS_LIBS" "`strip_l "$LIBVRB"`"
+        cnf_append "SDK_VBoxLibVorbis_INCS" "$INCVRB"
+        cnf_append "SDK_VBoxLibVorbis_LIBS" "`strip_l "$LIBVRB"`"
       fi
     else
       echo "not found -- building libvorbis from in-tree code."
@@ -1875,8 +1916,8 @@ EOF
     [ -n "$INCOGG" ] && I_INCVRB=`prefix_I "$INCOGG"`
     if test_compile "$LIBOGG $I_INCOGG" ogg ogg nofatal; then
       if test_execute; then
-        cnf_append "SDK_VBOX_OGG_INCS" "$INCOGG"
-        cnf_append "SDK_VBOX_OGG_LIBS" "`strip_l "$LIBOGG"`"
+        cnf_append "SDK_VBoxLibOgg_INCS" "$INCOGG"
+        cnf_append "SDK_VBoxLibOgg_LIBS" "`strip_l "$LIBOGG"`"
       fi
     else
       echo "not found -- building libogg from in-tree code."
@@ -2132,7 +2173,7 @@ extern "C" int main(void)
 }
 EOF
   found=
-  SUPPYTHONLIBS="python2.7 python2.6 python3.1 python3.2 python3.3 python3.4 python3.4m python3.5 python3.5m python3.6 python3.6m python3.7 python3.7m python3.8 python3.8m python3.9 python3.9m python3.10 python3.10m"
+  SUPPYTHONLIBS="python2.7 python2.6 python3.1 python3.2 python3.3 python3.4 python3.4m python3.5 python3.5m python3.6 python3.6m python3.7 python3.7m python3.8 python3.9 python3.10 python3.11 python3.12"
   for p in $PYTHONDIR; do
     for d in $SUPPYTHONLIBS; do
       for b in lib/x86_64-linux-gnu lib/i386-linux-gnu lib64 lib/64 lib; do
@@ -2478,6 +2519,7 @@ EOF
 [ $WITH_LIBVORBIS -eq 0 ] && echo "  --enable-libvorbis       enable system libvorbis"
 [ $WITH_LIBOGG -eq 0 ]  && echo "  --enable-libogg          enable system libogg"
 [ $WITH_LIBTPMS -eq 1 ] && echo "  --disable-libtpms        don't use libtpms for TPM emulation"
+[ $WITH_LIBLZMA -eq 1 ] && echo "  --disable-liblzma        don't use liblzma"
 [ "$OS" = "linux" -o "$OS" = "freebsd" ] && echo "  --enable-vde             enable VDE networking"
 cat << EOF
   --disable-udptunnel      disable UDP tunnel networking
@@ -2486,6 +2528,7 @@ cat << EOF
   --build-libxml2          build libxml2 from sources
   --build-libssl           build openssl from sources
   --build-libtpms          build libtpms from sources
+  --build-liblzma          build liblzma from sources
 EOF
 [ $OSE -eq 0 ] && cat << EOF
   --build-libcurl          build libcurl from sources
@@ -2725,6 +2768,9 @@ for option in "$@"; do
     --disable-libtpms)
       WITH_LIBTPMS=0
       ;;
+    --disable-liblzma)
+      WITH_LIBLZMA=0
+      ;;
     --enable-libogg)
       WITH_LIBOGG=1
       ;;
@@ -2751,6 +2797,12 @@ for option in "$@"; do
       ;;
     --build-libvpx)
       BUILD_LIBVPX=1
+      ;;
+    --build-libtpms)
+      BUILD_LIBTPMS=1
+      ;;
+    --build-liblzma)
+      BUILD_LIBLZMA=1
       ;;
     --build-headless)
       HEADLESS=1
@@ -2919,6 +2971,7 @@ fi
 [ $WITH_HARDENING -eq 2 ] && cnf_append "VBOX_WITH_HARDENING" "2"
 [ $WITH_VMMRAW    -eq 0 ] && cnf_append "VBOX_WITH_RAW_MODE" ""
 [ $WITH_LIBTPMS   -eq 0 ] && cnf_append "VBOX_WITH_LIBTPMS" ""
+[ $WITH_LIBLZMA   -eq 0 ] && cnf_append "VBOX_WITH_LIBLZMA" ""
 if [ $WITH_LIBVPX -eq 0 ]; then
   cnf_append "VBOX_WITH_LIBVPX" ""
   cnf_append "VBOX_WITH_RECORDING" ""
@@ -2954,6 +3007,7 @@ if [ $ONLY_ADDITIONS -eq 0 ]; then
   [ $WITH_LIBOGG -eq 1 ] && check_libogg
   [ $WITH_LIBVORBIS -eq 1 ] && check_libvorbis
   [ $WITH_LIBTPMS -eq 1 ] && check_libtpms
+  [ $WITH_LIBLZMA -eq 1 ] && check_liblzma
   [ "$OS" != "darwin"  ] && check_png
   [ $OSE -eq 0 -a "$OS" = "linux" ] && check_pam
   if [ $WITH_SDL -eq 1 ]; then
